<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Money movements — the single ledger.
     *
     * A table, not a column on `orders`, because a payment has a life of its
     * own: it is attempted, it fails, it is retried on another number, it
     * eventually succeeds, and months later it may be refunded. Collapsing that
     * into `orders.paid_at` throws away every attempt but the last — which is
     * exactly the history support needs when a client says they were debited.
     *
     * **Polymorphic, not `order_id`.** The same flow has to collect for a
     * charter booking and for a Mova Pass subscription. A foreign key to one of
     * them would mean a second payment system for the other, which is how a
     * codebase ends up with three ledgers that disagree — see the `transactions`
     * table this one absorbs.
     */
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid')->unique();

            /*
             * Order | PassSubscription | Reservation — anything implementing
             * the Payable contract. See App\Domain\Payment\Contracts\Payable.
             *
             * `payable_id` is a STRING, not the unsignedBigInteger `morphs()`
             * would give. Orders and subscriptions have integer keys but
             * Reservation uses HasUuids, and a bigint column cannot hold a
             * UUID — the row would be silently truncated to 0 and every
             * reservation payment would point at the same phantom record.
             */
            $table->string('payable_type');
            $table->string('payable_id', 64);
            $table->index(['payable_type', 'payable_id']);

            /*
             * Nullable, because not every payment has an app account behind it.
             * A counter agent collecting cash for a walk-in reservation is a
             * real payment with no client record, and forcing one would either
             * invent a ghost client or push that money back out of the ledger.
             */
            $table->foreignId('client_id')->nullable()->constrained()->cascadeOnDelete();

            /*
             * A string, not an enum cast.
             *
             * Providers are rows in `payment_providers`, added by ops without a
             * deploy. A PHP enum here would mean every new provider needs a
             * code change — the exact thing the driver registry exists to
             * avoid. Validity is checked against the providers table.
             */
            $table->string('provider_code')->index();

            /** app | back_office | system — where the attempt came from. */
            $table->string('channel')->default('app');

            /** full | deposit | balance | refund */
            $table->string('kind')->default('full');

            // Refunds and instalments point back at the payment they settle.
            $table->foreignId('parent_payment_id')->nullable()
                ->constrained('payments')->nullOnDelete();

            $table->string('status')->default('pending');

            /*
             * Whole francs, as integers. XAF has no subunit — the smallest coin
             * is one franc — so a decimal would only invite the rounding errors
             * money-as-float is famous for, for a fractional part that cannot
             * exist.
             */
            $table->unsignedInteger('amount');
            /** What the provider takes. Recorded, never inferred later. */
            $table->unsignedInteger('fee_amount')->default(0);
            /** What Mova actually receives. `amount` minus `fee_amount`. */
            $table->unsignedInteger('net_amount')->default(0);
            $table->string('currency', 3)->default('XAF');

            // The number the prompt was pushed to. May differ from the account
            // phone — people pay from a spouse's or an employer's wallet.
            $table->string('payer_phone')->nullable();

            /*
             * Generated by us, before the provider is called, and sent as the
             * provider's own request id where it accepts one (MTN's
             * X-Reference-Id). Unique, so a retried HTTP request cannot become
             * a second debit.
             */
            $table->string('idempotency_key')->unique();

            // The provider's id. Unique so a replayed webhook cannot create a
            // second record for one transaction.
            $table->string('provider_reference')->nullable()->unique();
            $table->text('failure_reason')->nullable();

            $table->timestamp('processing_at')->nullable();
            $table->timestamp('paid_at')->nullable();
            $table->timestamp('failed_at')->nullable();
            /** After this, reconciliation gives up and fails the attempt. */
            $table->timestamp('expires_at')->nullable();

            // Raw provider payloads, kept for reconciliation disputes.
            $table->json('meta')->nullable();

            // Set for back-office collections, so a cash entry is attributable.
            $table->foreignId('created_by')->nullable()
                ->constrained('users')->nullOnDelete();

            $table->timestamps();

            $table->index(['client_id', 'created_at']);
            $table->index(['status', 'processing_at']);
            $table->index(['provider_code', 'status']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
